# -*- coding: utf-8 -*-
"""Tarea#5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t5-vFm2ZRWI7bdgFu9eRl42zcEjrYMkI
"""

import random
import numpy as np
import matplotlib.pyplot as plt

class Cat:
    def __init__(self, alleles=[]):
        if not alleles:
            self.alleles = [random.choice(["A", "a"]) for _ in range(2)]
        else:
            self.alleles = [allele for allele in alleles]

    def reproduce(self, partner):
        child_alleles = [random.choice([self.alleles[0], partner.alleles[0]]),
                        random.choice([self.alleles[1], partner.alleles[1]])]
        return Cat(child_alleles)

    def get_genotype(self):
        return "".join(self.alleles)

    def get_eye_color(self):
        if self.alleles == ['A', 'A']:
            return 'Azul'
        if self.alleles == ['a','a']:
          return 'Naranja'
        if self.alleles == ['a','A']:
          return 'Verde'
        else:
          return 'Morado'

#La herencia se refiere a la transmisión de características
#genéticas de una generación a la siguiente.

# Creación de padre y madre, para su repoducción y generacion de la población
father = Cat(["A", "a"]) # Ojos de color Morado
mother = Cat(["a", "A"]) # Ojos de color Verde

population = [father.reproduce(mother) for _ in range(100)]

# Obtención de frecuencia de alelos y colores de ojos
allele_counts = {'aa': 0, 'Aa': 0, 'AA': 0, "aA": 0}
eye_colors = {'Azul': 0, 'Verde': 0, 'Naranja': 0, 'Morado':0}

for cat in population:
    genotype = cat.get_genotype()
    allele_counts[genotype] += 1
    eye_color = cat.get_eye_color()
    eye_colors[eye_color] += 1

# Extracción de etiquetas y valores para el gráfico
genotypes = list(allele_counts.keys())
count_values = list(allele_counts.values())

## Los alelos son variantes de un gen que determinan diferentes características
## o rasgos en un organismo y se encuentran en la misma posición en cromosomas homólogos.
##El genotipo es la combinación específica de alelos en un organismo,
##que determina su información genética heredada.

# Creación del gráfico de barras para la frecuencia de alelos
plt.bar(genotypes, count_values)
plt.xlabel('Genotipo')
plt.ylabel('Frecuencia')
plt.title('Frecuencia de Alelos en la Población de Gatos')
plt.show()

# Extracción de etiquetas y valores para el gráfico de colores de ojos
eye_color_labels = list(eye_colors.keys())
eye_color_values = list(eye_colors.values())

# Creación del gráfico de barras para la frecuencia de colores de ojos
plt.bar(eye_color_labels, eye_color_values, color=['blue', 'green', 'orange','purple'])
plt.xlabel('Color de Ojos')
plt.ylabel('Frecuencia')
plt.title('Frecuencia de Colores de Ojos en la Población de Gatos')
plt.show()